version: '3.8'
services:
  backend:
    build: .
    environment:
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ../backend:/app
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: